### ISSUE TITLE
Replace .env file in figma-to-react with .env.example for security reasons

### ISSUE THREAD

**Issue by charrismatic** [figma/figma-api-demo#28]
The `.env` file should not be tracked in the git repo under the `figma-to-react` folder. When the user adds their own key values the changes will be committed to the history. Instead you can include a `.env.example` file as a template or remove the file and outline how to create it in the readme file.

**Comment by coreyward** [comment]
Hi Matt, thanks for looking out for concerns like this. You’re absolutely right that in most circumstances it goes against best practices to commit secrets to a repository. In this case we’ve included the `.env` file here with a placeholder value deliberately for clarity and ease of reference since this is only a demo/example repo. We don’t expect others to be running this code in production or making commits back to this repository.
